### PR TITLE
[T-6939][17.0][ADD] partner_disable_vat_verification: disables partner vat verification.

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
[T-6939]

### CODE REVIEW

**Review by sara-castello — APPROVED** [review]
Functional review LGTM

**Comment by angelgarciadelachica** [comment]
@manuelregidor Can you check this PR? :-)
THX!

**Review by manuelregidor — APPROVED** [review]
Technical review. LGTM

**Comment by angelgarciadelachica** [comment]
@ValentinVinagre Can you merge? 
THX!

**Pull request merged**
